[obsidian]
src.webpage = "https://api.github.com/repos/obsidianmd/obsidian-releases/releases?per_page=100"
src.regex = "releases/download/v([0-9][0-9.]*)/Obsidian-[0-9][0-9.]*\\.AppImage\""
fetch.url = "https://github.com/obsidianmd/obsidian-releases/releases/download/v$ver/Obsidian-$ver.AppImage"

[sidra]
src.webpage = "https://api.github.com/repos/wimpysworld/sidra/releases?per_page=100"
src.regex = "releases/download/([0-9][0-9.]*)/Sidra-linux-x86_64\\.AppImage\""
fetch.url = "https://github.com/wimpysworld/sidra/releases/download/$ver/Sidra-linux-x86_64.AppImage"
