# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  obsidian = {
    pname = "obsidian";
    version = "1.13.7";
    src = fetchurl {
      url = "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.13.7/Obsidian-1.13.7.AppImage";
      sha256 = "sha256-4NjgphFiTejJx9zYqeZIJ5+woNVS+qExK35POl+nJmM=";
    };
  };
  sidra = {
    pname = "sidra";
    version = "1.1.2";
    src = fetchurl {
      url = "https://github.com/wimpysworld/sidra/releases/download/1.1.2/Sidra-linux-x86_64.AppImage";
      sha256 = "sha256-ON9b0VkPWRRW7+0TIw2Ygs464WYHeFigD+gfz/sEql4=";
    };
  };
}
