# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  obsidian = {
    pname = "obsidian";
    version = "1.13.7";
    src = fetchurl {
      url = "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.13.7/Obsidian-1.13.7.AppImage";
      sha256 = "sha256-4NjgphFiTejJx9zYqeZIJ5+woNVS+qExK35POl+nJmM=";
    };
  };
  openchamber = {
    pname = "openchamber";
    version = "1.19.0";
    src = fetchurl {
      url = "https://github.com/openchamber/openchamber/releases/download/v1.19.0/OpenChamber-1.19.0-linux-x86_64.AppImage";
      sha256 = "sha256-HrSI4Pd+0qxUXVc1o6CLC9LJlUbj4Nh4O4HVqgkOv4g=";
    };
  };
  sidra = {
    pname = "sidra";
    version = "0.4.1";
    src = fetchurl {
      url = "https://github.com/wimpysworld/sidra/releases/download/0.4.1/Sidra-linux-x86_64.AppImage";
      sha256 = "sha256-AnWPy7nWkTJu0ainFjU5jgoqmZki1ioyNwKSj3ymAsQ=";
    };
  };
}
